"""Generate palette overrides from the preserved green theme. Python stdlib only."""
from pathlib import Path
import re, colorsys
root=Path(__file__).resolve().parent.parent
css=(root/'src/ui/styles.css').read_text(encoding='utf-8')
colors=sorted(set(re.findall(r'#[a-fA-F0-9]{6}\b',css)))
semantic={'#c7e7a2','#40552c','#d4dfca','#49513c','#afda88','#36482b'}
result=['/* Generated by scripts/generate-themes.py. Green retains the original palette. */']
for name,hue in [('purple',270),('blue',216),('red',354)]:
    result.append(f':root[data-theme="{name}"] {{')
    for c in colors:
        rgb=[int(c[i:i+2],16)/255 for i in (1,3,5)]
        h,l,s=colorsys.rgb_to_hls(*rgb)
        if c in semantic: continue
        neutral=s<.28 and l<.5
        accent=65<=h*360<=150 and s>=.2
        board=c in {'#eeeed2','#769656','#526c37'}
        if not (neutral or accent or board):continue
        saturation=.24 if neutral else .48
        lightness=l*.87 if neutral else l
        if c=='#81b64c': lightness=.69
        if c=='#96c660': lightness=.76
        vals=colorsys.hls_to_rgb(hue/360,lightness,saturation)
        target='#'+''.join(f'{round(v*255):02x}' for v in vals)
        result.append(f'  --tone-{c[1:]}: {target};')
    result.append('}')
(root/'src/ui/themes.css').write_text('\n'.join(result)+'\n',encoding='utf-8')
